### ISSUE TITLE
Use git tags to easily relate git commit to pypi version

### ISSUE THREAD

**Issue by shadiakiki1986** [mljar/mljar-api-python#1]
Just my 2 cents:
ATM, it seems that there are no git tags in the repository,
which makes it non-straight-forward to figure out if a function parameter,
e.g. `fit(..., dataset_title)`,
is part of the 0.0.6 release on pypi.

Perhaps for 0.0.7 and later versions, you can just run `git tag 0.0.7 && git push origin 0.0.7` for the same version published to pypi

**Comment by pplonski** [comment]
Thank you! Will do :+1:
