### ISSUE TITLE
mljar.fit returning prediction from result not belong to my current experiment

### ISSUE THREAD

**Issue by shadiakiki1986** [mljar/mljar-api-python#2]
There are multiple experiments in my project.
When I ran `mljar.fit(...)` for my 2nd experiment,
I got results that looked like results from my 1st experiment.
Digging deeper, I found that the function `ResultClient(project id).get_results(experiment id)`
([link](https://github.com/mljar/mljar-api-python/blob/master/mljar/client/result.py#L14))
was not filtering the results for the experiment ID being passed.
For example, the code below

```

clf_mlj = Mljar(
  project='some project name',
  experiment='some experiment name',
  ...
)

from mljar.client.result import ResultClient
client = ResultClient(clf_mlj.project.hid)
results = client.get_results(clf_mlj.experiment.hid)
len(results) # returns 75
results = client.get_results(None)
len(results) # returns 75 as well
```

**Comment by pplonski** [comment]
Thank you! I'll work on that.

**Comment by pplonski** [comment]
Fixed!
