### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by shadiakiki1986** [mljar/mljar-api-python#4]
Hello. It seems that mljar is python2-compatible but not python3-compatible (e.g. some `print ...` calls without parentheses, the `from mljar import Mljar` call in `mljar.__init__`).
Any plan on releasing a python3-compatible version?

**Comment by pplonski** [comment]
Yes - I have a plan to do this.

**Comment by pplonski** [comment]
Done! Code should run run with python 2.7 or 3.6
