### ISSUE TITLE
columns get renamed when `predict` is called

### ISSUE THREAD

**Issue by shadiakiki1986** [mljar/mljar-api-python#5]
Hi. I used the `predict` method on a pandas dataframe with the same column names of the dataframe used in the `fit` method, but the columns with the `predict` method got renamed from `1` to `attribute_1`, `2` to `attribute_2`, etc. Is this because the column names are numeric?

**Comment by pplonski** [comment]
You are right - this is because the column names are numeric. If you want to keep your column name, please use other column name, for example `feature1` .
