### ISSUE TITLE
mljar.com app / new Experiment / Learning Algorithms is empty

### ISSUE THREAD

**Issue by shadiakiki1986** [mljar/mljar-api-python#8]
There used to be a list of checkboxes of algorithms to select from. Now it's empty.

**Comment by pplonski** [comment]
can you provide example how to reproduce this issue?

**Comment by shadiakiki1986** [comment]
I think this is not an issue that is specific to `mljar-api-python`, but a general issue in mljar.com.
If I click on "experiments" and "add new experiment", I get nothing under "use algorithm"

Screenshot

![screenshot from 2018-01-22 10-32-36](https://user-images.githubusercontent.com/8392324/35211593-cb896c78-ff5f-11e7-97ec-881d5d251897.png)

**Comment by pplonski** [comment]
looks like you didnt set a task for a project, how did you created the project? with python-api or with web ui? can you provide example? 

Thank you!

**Comment by shadiakiki1986** [comment]
The project was created around a year ago maybe.
It was created manually with mljar.com
The day before running into this issue, I think the list of algorithms were showing up.
But the same project is the one I'm using with the `mljar-python-api`, with example code same as in issue #6

**Comment by shadiakiki1986** [comment]
So do you mean that this issue is specific to my own project only?
If it is, I don't mind to just create a new project and work on it.

**Comment by pplonski** [comment]
Please try to create new project - if problem will occur please let me know. Thx!

**Comment by shadiakiki1986** [comment]
Just created a new project manually, but when I run `fit` with mljar-python-api (with the same project name), a new project with the same name is created, and indeed it doesn't have a "task" set

**Comment by shadiakiki1986** [comment]
I just realized that my target was continuous, whereas the original experiment was a binary classification. Reducing it to a binary class no longer creates a new experiment with the duplicated name.

**Comment by shadiakiki1986** [comment]
As this was fixed with my paying attention that the target should be binary when the experiment is a binary classification, feel free to close this issue
